export const state = () => ({
    showcase: [
        {
            title: 'Redditgetsdrawn',
            name: 'ulittlebluefleur',
            description: 'This is portrait of u/littlebluefleur, from /r/redditgetsdrawn.',
            finished: 'Apr 2019',
            thumbnail: '/thumbnails/ulittlebluefleur.png',
            hires: '/portraits/ulittlebluefleur.jpg',
            url: '/artwork/ulittlebluefleur',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Simone',
            name: 'simone',
            description: 'This is portrait of Simone, from /r/redditgetsdrawn.',
            finished: 'Apr 2019',
            thumbnail: '/thumbnails/simone.png',
            hires: '/portraits/simone.jpg',
            url: '/artwork/simone',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Ramon',
            name: 'ramon',
            description: 'This is portrait of Ramon, who emigrated here from Algeria. A portrait done by special request.',
            finished: 'Jan 2019',
            thumbnail: '/thumbnails/ramon.png',
            hires: '/portraits/ramon.jpg',
            url: '/artwork/ramon',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Keosha',
            name: 'keosha',
            description: 'Keosha is an entreprenuer from Florida. She works with children and is active in physical training on her own time.',
            finished: 'Sep 2018',
            thumbnail: '/thumbnails/keosha.png',
            hires: '/portraits/keosha.jpg',
            url: '/artwork/keosha',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Deya',
            name: 'deya',
            description: 'Deya is a sophomore at Skyline Highschool in Oakland, CA. She is a swimmer, and an aspiring doctor.',
            finished: 'Jun 2018',
            thumbnail: '/thumbnails/deya.png',
            hires: '/portraits/deya.jpg',
            url: '/artwork/deya',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Meredith',
            name: 'meredith',
            description: 'Meredith is a figure model at a local drawing group in Berkeley, CA.',
            finished: 'May 2018',
            thumbnail: '/thumbnails/meredith.png',
            hires: '/portraits/meredith.jpg',
            url: '/artwork/meredith',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Neo',
            name: 'neo',
            description: 'Neo is a figure model at a local drawing group in Berkeley, CA.',
            finished: 'Mar 2018',
            thumbnail: '/thumbnails/neo.png',
            hires: '/portraits/neo.jpg',
            url: '/artwork/neo',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Abigail',
            name: 'abigail',
            description: 'Abigail is a figure model at a local drawing group in Berkeley, CA.',
            finished: 'Jan 2018',
            thumbnail: '/thumbnails/abigail-02.png',
            hires: '/portraits/abigail-02.jpg',
            url: '/artwork/abigail',
            portrait: false,
            showcase: false,
            sketchbook: false,
        }
    ],
    portraits: [
        {
            title: 'Redditgetsdrawn',
            name: 'ulittlebluefleur',
            description: 'This is portrait of u/littlebluefleur, from /r/redditgetsdrawn.',
            finished: 'Apr 2019',
            thumbnail: '/thumbnails/ulittlebluefleur.png',
            hires: '/portraits/ulittlebluefleur.jpg',
            url: '/artwork/ulittlebluefleur',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Simone',
            name: 'simone',
            description: 'This is portrait of Simone, from /r/redditgetsdrawn.',
            finished: 'Apr 2019',
            thumbnail: '/thumbnails/simone.png',
            hires: '/portraits/simone.jpg',
            url: '/artwork/simone',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Ramon',
            name: 'ramon',
            description: 'This is portrait of Ramon, who emigrated here from Algeria. A portrait done by special request.',
            finished: 'Jan 2019',
            thumbnail: '/thumbnails/ramon.png',
            hires: '/portraits/ramon.jpg',
            url: '/artwork/ramon',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Keosha',
            name: 'keosha',
            description: 'Keosha is an entreprenuer from Florida. She works with children and is active in physical training on her own time.',
            finished: 'Sep 2018',
            thumbnail: '/thumbnails/keosha.png',
            hires: '/portraits/keosha.jpg',
            url: '/artwork/keosha',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Deya',
            name: 'deya',
            description: 'Deya is a sophomore at Skyline Highschool in Oakland, CA. She is a swimmer, and an aspiring doctor.',
            finished: 'Jun 2018',
            thumbnail: '/thumbnails/deya.png',
            hires: '/portraits/deya.jpg',
            url: '/artwork/deya',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Meredith',
            name: 'meredith',
            description: 'Meredith is a figure model at a local drawing group in Berkeley, CA.',
            finished: 'May 2018',
            thumbnail: '/thumbnails/meredith.png',
            hires: '/portraits/meredith.jpg',
            url: '/artwork/meredith',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Neo',
            name: 'neo',
            description: 'Neo is a figure model at a local drawing group in Berkeley, CA.',
            finished: 'Mar 2018',
            thumbnail: '/thumbnails/neo.png',
            hires: '/portraits/neo.jpg',
            url: '/artwork/neo',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Abigail',
            name: 'abigail',
            description: 'Abigail is a figure model at a local drawing group in Berkeley, CA.',
            finished: 'Jan 2018',
            thumbnail: '/thumbnails/abigail-02.png',
            hires: '/portraits/abigail-02.jpg',
            url: '/artwork/abigail',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Reddit',
            name: 'reddit-02',
            description: 'No description.',
            finished: 'Jan 2018',
            thumbnail: '/thumbnails/unnamed-01.png',
            hires: '/portraits/ubookinz.png',
            url: '/artwork/reddit-02',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Kalena',
            name: 'kalena',
            description: 'Acrylic on cardboard.',
            finished: 'Jan 2018',
            thumbnail: '/thumbnails/kalena.png',
            hires: '/portraits/kalena.png',
            url: '/artwork/kalena',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Reddit',
            name: 'reddit-01',
            description: 'No description.',
            finished: 'Apr 2019',
            thumbnail: '/thumbnails/unnamed-03.png',
            hires: '/portraits/unnamed-03.png',
            url: '/artwork/reddit-01',
            portrait: false,
            showcase: false,
            sketchbook: false,
        },
        {
            title: 'Study 1',
            name: 'study-01',
            description: 'No description.',
            finished: 'Jan 2017',
            thumbnail: '/thumbnails/unnamed-04.png',
            hires: '/portraits/unnamed-04.png',
            url: '/artwork/study-01',
            portrait: false,
            showcase: false,
            sketchbook: false,
        }
  ],
  sketchbook: [
        {
            name: '',
            thumbnail: '/sketchbook/sketchbook-01.png'
        },
        {
            name: '',
            thumbnail: '/sketchbook/sketchbook-02.png'
        },
        {
            name: '',
            thumbnail: '/sketchbook/sketchbook-03.png'
        },
        {
            name: '',
            thumbnail: '/sketchbook/sketchbook-04.png'
        },
        {
            name: '',
            thumbnail: '/sketchbook/sketchbook-05.png'
        },
  ]
})